---
title: "Testing R Code"
description: "Checking how r code runs inside a blog post"
author: "Piers York"
date: "2022-07-10"
echo: false
toc: false
draft: true
---

```{r}
#| echo: false
#| message: false
library(ggplot2)
library(owidR)

my_theme <- function() {
    theme_owid(import_fonts = FALSE) + 
    theme(axis.title = element_blank(), text = element_text(size = 20), plot.title = element_text(size = 34), 
          plot.background = element_rect(fill = "#F0F6FF", colour = "#718199"))
} 
theme_set(my_theme())

human_rights <- owid("human-rights-scores", rename = "rights")

owid_plot(human_rights, filter = c("United Kingdom", "France", "China")) +
    labs(title = "Human Rights Scores") +
    my_theme()
    


```


## Test one
This is a test

## Test two
This post includes R code

```{r}
#| column: screen

library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng = -0.135341, lat = 51.49778, popup="Westminster, UK")
```

349871985, -0.13534160609779056