project:
  type: website
  output-dir: docs

website:
  title: "Piers York"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Software
        file: packages.qmd
      - text: Data blog
        href: blog/index.qmd
    right:
      - icon: github
        href: https://github.com/piersyork
      - icon: linkedin
        href: https://www.linkedin.com/in/piers-york/

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



