project:
  type: website
  output-dir: docs

website:
  title: "Piers York"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Software
        file: packages.qmd
      - text: Data blog
        href: blog/index.qmd
    right:
      - icon: github
        href: https://github.com/piersyork
      - icon: linkedin
        href: https://www.linkedin.com/in/piers-york/
  
  page-footer: 
    left: "&#169; Copyright 2022, Piers York"
    right: 
      - icon: github
        href: https://github.com/piersyork
      - icon: linkedin
        href: https://www.linkedin.com/in/piers-york/
      - icon: twitter
        href: https://twitter.com/piers_york
    background: light

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



